version: "3"
services:
  grpc-server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - go-grpc-server-with-envoy

  gateway-envoy:
    build:
      context: ./config
      dockerfile: Dockerfile
    ports:
      - "8083:8080"

    networks:
      - go-grpc-server-with-envoy

networks:
  go-grpc-server-with-envoy:
    driver: bridge
